[package]
org = "SumayyaTestOrg"
name = "InventoryAPI"
version = "1.0.0"
export = ["InventoryAPI"]
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "SumayyaTestOrg"
name = "FaresAPI"
version = "1.0.0"
repository = "local"
