[package]
org = "SumayyaTestOrg"
name = "ReservationAPI"
version = "1.0.0"
export = ["ReservationAPI"]
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "SumayyaTestOrg"
name = "InventoryAPI"
version = "1.0.0"
repository = "local"

[[dependency]]
org = "SumayyaTestOrg"
name = "BookingAPI"
version = "1.0.0"
repository = "local"
